name: Makefile CI

on:
  push:
    branches: [ "main", "v3" ]
  pull_request:
    branches: [ "main", "v3" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18.2'
    - name: Run Build
      run: |
        make all
